package vistas;

import javax.swing.Timer;
import metodosDAO.HoraActual;

/**
 *
 * @author Martin
 */

public final class pnl_principal extends javax.swing.JPanel {

    /**
     * Creates new form pnl_principal
     */
    public pnl_principal() {
        initComponents();
        ActualizarHora();
    }

    public void ActualizarHora() {
        Timer tiempo = new Timer(100, new HoraActual());
        tiempo.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fotoHotel = new javax.swing.JLabel();
        txtNombre = new javax.swing.JLabel();
        txtApellido = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        btnBordeFondo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtHora = new javax.swing.JLabel();
        btnBordeFondo1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 1, 50)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("HOTEL CORAL");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 400, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Datos del Trabajador");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, -1));

        txtCorreo.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(255, 255, 255));
        txtCorreo.setText("@gmail.com");
        add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Apellido:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, -1, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Correo  :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, 230, 40));

        fotoHotel.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        fotoHotel.setForeground(new java.awt.Color(255, 255, 255));
        fotoHotel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fotoHotel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgIcons/imgHotelCoral.jpg"))); // NOI18N
        add(fotoHotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 600, 399));

        txtNombre.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.setText("nameUsuario");
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, -1, -1));

        txtApellido.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(255, 255, 255));
        txtApellido.setText("lastNameUsuario");
        add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, -1, -1));

        jSeparator1.setToolTipText("");
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 240, 10));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nombre:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, -1, -1));

        btnBordeFondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        add(btnBordeFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 620, 420));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Correo  :");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, -1, -1));

        txtHora.setFont(new java.awt.Font("Century Schoolbook", 0, 20)); // NOI18N
        txtHora.setForeground(new java.awt.Color(255, 255, 255));
        txtHora.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 20, 210, 30));

        btnBordeFondo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        add(btnBordeFondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 330, 320));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBordeFondo;
    private javax.swing.JLabel btnBordeFondo1;
    private javax.swing.JLabel fotoHotel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JLabel txtApellido;
    public static javax.swing.JLabel txtCorreo;
    public static javax.swing.JLabel txtHora;
    public static javax.swing.JLabel txtNombre;
    // End of variables declaration//GEN-END:variables
}
